### ISSUE TITLE
Noob have problem...

### ISSUE THREAD

**Issue by Thetiti999** [chris54721/OpenMCAuthenticator#2]
Hello,

I french noob sorry,

My class work ecxept 	}  catch (ResponseException e) { 

help me pls
Thanks

**Comment by chris54721** [comment]
I'll need a bit more info to help you. What do you mean by "doesn't work"?

**Comment by Thetiti999** [comment]
On my projet,
I correct import whtih graddle and you code work just ResponseException e 
is "ResponseException cannot be resolved to a type"
http://i.imgur.com/BSSiDjv.png
Thanks

**Comment by chris54721** [comment]
That'd be `RequestException` instead of `ResponseException`. I changed the class name but forgot to update the README. Thanks 👍
